Add missing getter
javax.el.PropertyNotFoundException: Property 'pisteetToDisplay' not found on type fi.vm.sade.haku.oppija.hakemus.domain.dto.Pistetieto