Have to use List instead of Map for groupaddresses
Because:
org.springframework.data.mapping.model.MappingException: Map key 1.2.246.562.28.00000000012 contains dots but no replacement was configured!
Make sure map keys don't contain dots in the first place or configure an appropriate replacement!
at org.springframework.data.mongodb.core.convert.MappingMongoConverter.potentiallyEscapeMapKey(MappingMongoConverter.java:580)